setwd('R:/')
pacman::p_load(dplyr)

dat<-readxl::read_xlsx('4_with episode_wideform_2009.xlsx')
data<-dat %>% filter(sex!=3)


t.test(가족~sex, data= data)
t.test(가족과직장~sex, data= data)
t.test(가족의건강~sex, data= data)
t.test(가족과갈등~sex, data= data)
t.test(가족의죽음~sex, data= data)
t.test(직장~sex, data= data)
t.test(건강~sex, data= data)
t.test(취업~sex, data= data)
t.test(취업과학업~sex, data= data)
t.test(취업의실패~sex, data= data)
t.test(코로나~sex, data= data)
t.test(본인학업~sex, data= data)
t.test(대인관계~sex, data= data)
t.test(경제문제~sex, data= data)
t.test(돌봄~sex, data= data)
t.test(연인과이별~sex, data= data)
t.test(주거~sex, data= data)
t.test(사건사고~sex, data= data)
t.test(정신건강~sex, data= data)
t.test(열등감~sex, data= data)
t.test(가족형태변화~sex, data= data)
t.test(실직~sex, data= data)
t.test(학대폭력성범죄~sex, data= data)
t.test(신체와외모~sex, data= data)
t.test(미래~sex, data= data)
t.test(반려동물~sex, data= data)
t.test(사회이슈~sex, data= data)
t.test(자살과자해~sex, data= data)
t.test(임신과출산~sex, data= data)
t.test(유학~sex, data= data)
t.test(군복무~sex, data= data)
t.test(배신~sex, data= data)
t.test(법적문제~sex, data= data)
t.test(명절~sex, data= data)
t.test(재난~sex, data= data)



setwd('R:/')
pacman::p_load(dplyr)

data<-readxl::read_xlsx('4_with episode_wideform_2009.xlsx')

data$age<-ifelse(data$age<30, 1,
                 ifelse(data$age<40,2,
                        ifelse(data$age<50,3,4)))
data$age<-as.factor(data$age)


summary(aov(가족~age, data= data))
summary(aov(가족과직장~age, data= data))
summary(aov(가족의건강~age, data= data))
summary(aov(가족과갈등~age, data= data))
summary(aov(가족의죽음~age, data= data))
summary(aov(직장~age, data= data))
summary(aov(건강~age, data= data))
summary(aov(취업~age, data= data))
summary(aov(취업과학업~age, data= data))
summary(aov(취업의실패~age, data= data))
summary(aov(코로나~age, data= data))
summary(aov(본인학업~age, data= data))
summary(aov(대인관계~age, data= data))
summary(aov(경제문제~age, data= data))
summary(aov(돌봄~age, data= data))
summary(aov(연인과이별~age, data= data))
summary(aov(주거~age, data= data))
summary(aov(사건사고~age, data= data))
summary(aov(정신건강~age, data= data))
summary(aov(열등감~age, data= data))
summary(aov(가족형태변화~age, data= data))
summary(aov(실직~age, data= data))
summary(aov(학대폭력성범죄~age, data= data))
summary(aov(신체와외모~age, data= data))
summary(aov(미래~age, data= data))
summary(aov(반려동물~age, data= data))
summary(aov(사회이슈~age, data= data))
summary(aov(자살과자해~age, data= data))
summary(aov(임신과출산~age, data= data))
summary(aov(유학~age, data= data))
summary(aov(군복무~age, data= data))
summary(aov(배신~age, data= data))
summary(aov(법적문제~age, data= data))
summary(aov(명절~age, data= data))
summary(aov(재난~age, data= data))


data %>% group_by(age) %>% summarise(count = n())
data %>% group_by(가족,age) %>% summarise(count = n())
data %>% group_by(가족의건강,age) %>% summarise(count = n())
data %>% group_by(가족의죽음,age) %>% summarise(count = n())
data %>% group_by(건강,age) %>% summarise(count = n())
data %>% group_by(취업,age) %>% summarise(count = n())
data %>% group_by(취업과학업,age) %>% summarise(count = n())
data %>% group_by(취업의실패,age) %>% summarise(count = n())
data %>% group_by(코로나,age) %>% summarise(count = n())
data %>% group_by(본인학업,age) %>% summarise(count = n())
data %>% group_by(대인관계,age) %>% summarise(count = n())
data %>% group_by(경제문제,age) %>% summarise(count = n())
data %>% group_by(돌봄,age) %>% summarise(count = n())
data %>% group_by(연인과이별,age) %>% summarise(count = n())
data %>% group_by(주거,age) %>% summarise(count = n())
data %>% group_by(열등감,age) %>% summarise(count = n())
data %>% group_by(가족형태변화,age) %>% summarise(count = n())
data %>% group_by(실직,age) %>% summarise(count = n())
data %>% group_by(미래,age) %>% summarise(count = n())
data %>% group_by(임신과출산,age) %>% summarise(count = n())
